### ISSUE TITLE
search crashing

### ISSUE THREAD

**Issue by mircealungu** [zeeguu-ecosystem/Unified-Multilanguage-Reader#323]
i wonder if this happens because i didn't run the map_article_words script.
even so, it should not happen.

```
10.0.2.2 - - [31/May/2018 07:13:15] "GET /search/metoo?session=17628441 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/mircea/.venvs/zenv/lib/python3.6/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/mircea/.venvs/zenv/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/mircea/.venvs/zenv/lib/python3.6/site-packages/Flask_Cors-3.0.3-py3.6.egg/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/mircea/.venvs/zenv/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mircea/.venvs/zenv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/mircea/.venvs/zenv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mircea/.venvs/zenv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mircea/.venvs/zenv/lib/python3.6/site-packages/Flask_Cors-3.0.3-py3.6.egg/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/mircea/.venvs/zenv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mircea/.venvs/zenv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/mircea/.venvs/zenv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mircea/.venvs/zenv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mircea/.venvs/zenv/lib/python3.6/site-packages/flask_monitoringdashboard/measurement.py", line 95, in wrapper
    return func(*args, **kwargs)
  File "/home/mircea/Zeeguu-API/zeeguu_api/api/utils/route_wrappers.py", line 43, in wrapped_view
    response = flask.make_response(view(*args, **kwargs))
  File "/home/mircea/Zeeguu-API/zeeguu_api/api/utils/route_wrappers.py", line 29, in wrapped_view
    return view(*args, **kwargs)
  File "/home/mircea/Zeeguu-API/zeeguu_api/api/search.py", line 182, in search_for_search_terms
    return json_result(article_search_for_user(flask.g.user, 20, search_terms))
  File "/home/mircea/Zeeguu-Core/zeeguu/content_recommender/mixed_recommender.py", line 82, in article_search_for_user
    final = [article for article in search_articles if article in all_articles]
TypeError: 'NoneType' object is not iterable

```

**Comment by Feikoritsema** [comment]
It's a core issue, will fix it in a minute, indeed shouldn't happen.
